#!/bin/bash
set -e

source /usr/local/bin/toolchain.sh

case "${1:-}" in
    -l|--list) exec /usr/local/bin/list-toolchains ;;
esac

if [ $# -eq 0 ]; then
    echo "[k230] error: no toolchain specified" >&2
    echo "[k230] usage: download-toolchains <TC1..TC6|linux|rtos|rt-smart|nuttx|llvm|all> [...]" >&2
    echo "[k230] run 'download-toolchains -l' to list toolchains" >&2
    exit 2
fi

declare -A done
for arg in "$@"; do
    set_list="$(resolve_toolchain_set "$arg")" || {
        echo "[k230] error: unknown toolchain '$arg'" >&2
        exit 1
    }
    for tc in $set_list; do
        [ -n "${done[$tc]:-}" ] && continue
        done[$tc]=1
        "download_$tc"
    done
done
